### ISSUE TITLE
Registering with Hue Bridge hangup

### ISSUE THREAD

**Issue by gotteric** [kershner/screenBloom#26]
After clicking register, it seems to stay on the loading overlay indefinitely. So far I have tried:
- Uninstalling/reinstalling
- Starting it normally and with admin
- Registering by /new-user and by /manual

All have had the same result.

Other relevant stuff I can think of:
- screenBloom version - 2.2 (win10)
- Hue Bridge software version - 01036659
- When trying to go to the server page (after attempting to register) it gives an internal server error with error text 'colormode'

Not sure if there is something simple I've overlooked.. Thanks in advance for the help!

**Comment by pauliftw** [comment]
Delete the 2.2 install. Use the 2.1 version instead still works. I cant register 2.2 with bridge also tried all i could think off. Or try unpowering bridge and unplug utp and router reset.

**Comment by Scharmen** [comment]
Same problem here. 

Version 2.1 isn't working as well ( in my case). 
  +Registration is working
  - Controlling the blubs isn't working (Error in app: Exception on /update-blubs)

**Comment by kershner** [comment]
Hey guys - thanks for opening this issue.  

I'm fairly certain I know what the problem is and I have some user data to help fix it.  I will for sure have a fix by the end of the weekend, but probably sooner.

In the meantime, more data is good data, so if you guys could post your config files, that would be a big help!

It's located in

**c:/Users/your_username/AppData/Roaming/screenBloom/screenbloom_config.cfg**

* You'll need to enable 'Show Hidden Files' to see the AppData directory.

Thanks for your patience!

**Comment by Kakifrucht** [comment]
Or just navigate to ``%APPDATA%/screenBloom`` in Windows explorer.

**Comment by Scharmen** [comment]
ScreenBloom v2.1
[screenBloom_config.zip](https://github.com/kershner/screenBloom/files/815028/screenBloom_config.zip)

**Comment by kershner** [comment]
Hey everyone,

I think I might have fixed it.  Can you guys test it for me?

[http://kershner.org/static/distribute/screenBloom_test.zip](http://kershner.org/static/distribute/screenBloom_test.zip)

**Comment by Scharmen** [comment]
Unfortunately, it isn't working. 

Still can't register (endless loop). If I'm trying to start the installed program a second time I get a Python Error Window (See picture). 
![pythonerror](https://cloud.githubusercontent.com/assets/18516436/23546714/1d8c736c-0001-11e7-8ff1-b97a36bb475a.PNG)

**Comment by gotteric** [comment]
Also still having an issue.  Here is the contents of my config file:

`[Configuration]`
`hue_ip = 192.168.1.243`
`username = D5Y-7MOlYJSWmCPJ5U4O35O2gyUMyRfizU-dEXTq`
`auto_start = 0`
`current_preset = `
``
`[Light Settings]`
`all_lights = 3,4,7,6`
`active = 0,0,0,0`
`bulb_settings = {"3": {"max_bri": 254, "min_bri": 1}, "4": {"max_bri": 254, "min_bri": 1}, "7": {"max_bri": 254, "min_bri": 1}, "6": {"max_bri": 254, "min_bri": 1}}`
`update = 0.7`
`update_buffer = 0`
`default = `
`max_bri = 254`
`min_bri = 1`
`zones = []`
`zone_state = 0`
`display_index = 0`
`sat = 1.0`
``
`[Party Mode]`
`running = 0`
``
`[App State]`
`running = False`
``
``

**Comment by kershner** [comment]
Ok, I was afraid of that lol.  Sorry to make you guys jump through all these hoops.  I've also fixed the XY keyerror, that fix is in the live version on [screenbloom.com](screenbloom.com).  Hopefully this will be the last time you have to re-install!

Let me know if that ends up working for you guys.

Also, if you get the time - can you tell me what Hue lights you guys have?  A certain type is causing all kinds of issues, I think it's related to the non-color bulbs.

**Comment by Scharmen** [comment]
I am sorry to bring you the bad news, but still not working for me. 

I am using
- 6x Color bulb (Gen 2) E27
- 1x Color bulb GU10
- 1x Ambiance Bulb
- 1x Living Colors (no hue version)
- 1x Lightify Plug

I hope it will help.

**Comment by kershner** [comment]
Man the different light setups are really not well documented at all with the Hue API.

So, you go to click 'Register' and it hangs there, like always, right?  Can you then try to launch the app again, you should probably get an error message.  Can you send me that error message?

Basically what I think I'm gonna have to do, if you're willing to keep helping me test, is I'll send you a modified file or a script which will give me a readout of all the light data structures your bridge is reporting.  That way I can see exactly which one is causing the problem (that Lightify plug looks suspicious haha,  never even heard of that one).

Do you have Python installed on your PC?  That'd make things a bit faster as I wouldn't have to compile an EXE for a simple script.

**Comment by Scharmen** [comment]
Yes, it hangs at the registration. 
![pythonerror](https://cloud.githubusercontent.com/assets/18516436/23562229/eb455072-0041-11e7-9ee8-3d9fd4689eb5.PNG)

Of course, I will help you. 
I don't need an .exe version, just send me the python script.

**Comment by gotteric** [comment]
Ditto, I'm happy to help, though my response time depends on if I am home of course. And I also have python already. 

For my lights I have:
- 2 white only
- 1 color bulb, gen 2
- 1 color strip

**Comment by kershner** [comment]
@gotteric did you try the test version or the new live version from screenbloom.com?  I think with your bulb setup it should work.

@Scharmen thanks for the error readout.  I think it's becoming clearer what the problem is.  As part of registration (and lots of other functions within the codebase) ScreenBloom will query your Hue bridge and build a dictionary of commonly used values for each light.  These errors are cropping up because there are apparently some Hue lights that are apparently missing key->value pairs (although not documented).

The error you got is saying one of your lights is missing the **bri** key, which makes no sense because that is functionality that should be supported by every single Hue product.

With all the lights you've mentioned, are you able to control all of them via the Hue app?  Color, brightness, etc?  Or are there some that can't be manipulated using the official Hue app?

I'll cook up the debug script later tonight or tomorrow and send it along.  Thanks so much for helping, guys.

**Comment by Scharmen** [comment]
@kershner Oh I forgot some Devices. 
First at all, I can use all my Bulb and the Plug with the Philips Hue app. The Plug just turns on and off. 

The additional devices are:
- 1x Hue Motion Sensor
-  2x Dimmer Switch

**Comment by kershner** [comment]
I can almost guarantee that the Plug is the issue.  You're saying it just turns on and off, which would be consistent with it missing a **bri** key->value.  Should be pretty simple to confirm and then fix.  Once I get a look at all the actual data structures I'll know for sure.

**Comment by Scharmen** [comment]
Great to hear you found the problem. I hope you don't have to much work because of my setup.

**Comment by kershner** [comment]
Ok, I have a little debug version ready to go.

[http://kershner.org/static/distribute/screenBloom_test.zip](http://kershner.org/static/distribute/screenBloom_test.zip)

What this will do is dump the light data from the Hue bridge to a file called **LIGHT_DATA.txt** inside the directory.  If your config file doesn't exist yet it'll dump the data just after you register with the bridge.  But if you already have a file, which you probably will if you downgraded back to 2.1, it'll just dump it immediately upon startup.

Once the data dump is done the program will take a key input and then crash.  Send me the contents of the LIGHT_DATA.txt file or the file itself and then you can delete the debug version if you want.

There is a chance Windows will give you grief about permissions, since it wants to write to a file on the harddrive.  Running the .exe as an admin should fix that if you run into it.

Let me know if you have any questions and thanks again!

**Comment by kershner** [comment]
That was fast!  

And yes, it looks like it is indeed the Osram Plug that is missing attributes.  My fix is to just skip lights that don't have a **bri** attribute, because that is the most basic level of functionality that ScreenBloom can manipulate.

Here's what I think will be the final version
[http://kershner.org/static/distribute/screenBloom_2.2_win.zip](http://kershner.org/static/distribute/screenBloom_2.2_win.zip)

Should be good to go, just let me know if you run into any issues.

**Comment by Scharmen** [comment]
I am sorry, but I still get the same issue.

![pythonerror](https://cloud.githubusercontent.com/assets/18516436/23582802/3ea55586-0133-11e7-8334-39cf07b1e582.PNG)

**Comment by kershner** [comment]
That's pretty odd, there is [now handling](https://github.com/kershner/screenBloom/blob/master/app/modules/hue_interface.py#L29) for that exact KeyError.  Makes me think it's a caching issue.  Try the classic uninstall previous version, reboot, install this new version.

If you want to make double sure you can open up the **hue_interface.py**  and check line 29 like I linked earlier.  If that try/catch isn't there then it's gotta be a cached version.

**Comment by Scharmen** [comment]
> That was fast!
> 
> And yes, it looks like it is indeed the Osram Plug that is missing attributes. My fix is to just skip lights that don't have a bri attribute, because that is the most basic level of functionality that ScreenBloom can manipulate.
> 
> Here's what I think will be the final version
> http://kershner.org/static/distribute/screenBloom_2.2_win.zip
> 
> Should be good to go, just let me know if you run into any issues.

I installed the version of your post. 
I think you compiled an old version of the hue_interface.py file.
There is no Error handling for 'bri' (please see screenshot):

<img width="646" alt="hue_interface py_screenshot" src="https://cloud.githubusercontent.com/assets/18516436/23586142/b0733d7a-018f-11e7-81ea-940457d99f52.png">

File (C:\Program\Screenbloom\ hue_interface.py)
[hue_interface.py.zip](https://github.com/kershner/screenBloom/files/819225/hue_interface.py.zip)

**Comment by kershner** [comment]
Wow I have no clue how that happened other than I'm an idiot.  Just re-uploaded it and verified that the files are correct.  Sorry about that!

**Comment by gotteric** [comment]
Finally got to try again. Everything is working for me with the new version on the screenbloom site. Thanks!

**Comment by Scharmen** [comment]
- Registration worked
- Updating Blubs doesn't work
- Second use of the Software led
![pythonerror](https://cloud.githubusercontent.com/assets/18516436/23620191/54abf2a4-0296-11e7-9bbb-74a4cd72f864.PNG)

**Comment by kershner** [comment]
Welp OK.  I was hoping this wouldn't be an issue but I know how to fix it, just need to find the time.  Will definitely be sometime this week.  I'll keep you posted.

**Comment by kershner** [comment]
Alright this one should definitely do it.
[http://kershner.org/static/distribute/screenBloom_test.zip](http://kershner.org/static/distribute/screenBloom_test.zip)

Lemme know how it goes and as always thanks for your patience!

**Comment by Scharmen** [comment]
It is working.

Great job, thank you!

**Comment by kershner** [comment]
Glad to hear it! 

Thanks again to everyone for all of the feedback.

Going to close this issue now, feel free to raise more if you run into further problems.
